FROM python:3.11

COPY lch /app/lch
COPY resources /app/resources

CMD [ "pip", "install", "-r", "requirements.txt" ]

ENV GITHUB_AUTH_TOKEN=
ENV DEFAULT_QUANTITY_OF_ITEMS_TO_FETCH=50
ENV TOTAL_QUANTITY_OF_REPOSITORIES=1_000
ENV PERSIT_GRAPQHL_QUERIES=1
